# Generated by Django 4.2.4 on 2023-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('name', models.CharField(max_length=10, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=10)),
                ('upgrade', models.CharField(max_length=2)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
