# Generated by Django 4.2.4 on 2023-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Get',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
