# Generated by Django 3.2.20 on 2023-08-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='get',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
