# Generated by Django 3.2.20 on 2023-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0002_auto_20230816_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get',
            name='last_update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
